<?xml version="1.0"?>
<!--
  Copyright 2015 Fadri Furrer, ASL, ETH Zurich, Switzerland
  Copyright 2015 Michael Burri, ASL, ETH Zurich, Switzerland
  Copyright 2015 Mina Kamel, ASL, ETH Zurich, Switzerland
  Copyright 2015 Janosch Nikolic, ASL, ETH Zurich, Switzerland
  Copyright 2015 Markus Achtelik, ASL, ETH Zurich, Switzerland

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
<!--  <xacro:include filename="$(find rotors_description)/urdf/material_properties.gazebo.xacro"/>-->
  <!-- Macro for the inertia of a box -->
  <xacro:macro name="box_inertia" params="x y z mass">
    <inertia ixx="${0.0833333 * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
      iyy="${0.0833333 * mass * (x*x + z*z)}" iyz="0.0"
      izz="${0.0833333 * mass * (x*x + y*y)}" />
  </xacro:macro>

  <!-- Macro for the inertial properties of a box -->
  <xacro:macro name="box_inertial" params="x y z mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <xacro:box_inertia x="${x}" y="${y}" z="${z}" mass="${mass}" />
    </inertial>
  </xacro:macro>

  <!-- Main multirotor link -->
  <xacro:macro name="multirotor_base_macro"
    params="robot_namespace mass body_width body_height use_mesh_file mesh_file *inertia">
 
	<link name="world"/>

  	<joint name="base_joint_fixed" type="fixed">
    	<parent link="world"/>
    	<child link="${robot_namespace}/base_link"/>
  	</joint>

    <link name="${robot_namespace}/base_link"></link>
	<gazebo reference = "${robot_namespace}/base_link">
		<gravity>false</gravity>
	</gazebo>
    <joint name="${robot_namespace}/base_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${robot_namespace}/base_link" />
      <child link="${robot_namespace}/base_link_inertia" />
    </joint>

              <!--led 0 joint \ link \ material-->
    <joint name="${robot_namespace}/led_joint_0" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${robot_namespace}/base_link" />
      <child link="led_link_0" />
    </joint>

    <link name="led_link_0"><!--red-->
      <visual>
        <origin xyz="0 0.165 -0.08" rpy="0 0 0" />
        <geometry>
          <cylinder radius="0.01" length="0.02"/>
        </geometry>
      </visual>
    </link>

    <gazebo reference="led_link_0">
      <visual>
        <material>
          <ambient>0 0 0 1</ambient>
          <diffuse>0 0 0 1</diffuse>
          <specular>0 0 0 1</specular>
          <emissive>1 0 0 1</emissive>
        </material>
      </visual>
    </gazebo>

                  <!--led 1 joint \ link \ material-->
    <joint name="${robot_namespace}/led_joint_1" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${robot_namespace}/base_link" />
      <child link="led_link_1" />
    </joint>

    <link name="led_link_1"><!--blue-->
      <visual>
        <origin xyz="-0.165 0 -0.08" rpy="0 0 0" />
        <geometry>
          <cylinder radius="0.01" length="0.02"/>
        </geometry>
      </visual>
    </link>

    <gazebo reference="led_link_1">
      <visual>
        <material>
          <ambient>0 0 0 1</ambient>
          <diffuse>0 0 0 1</diffuse>
          <specular>0 0 0 1</specular>
          <emissive>0 0 1 1</emissive>
        </material>
      </visual>
    </gazebo>
                    <!--led 2 joint \ link \ material-->
    <joint name="${robot_namespace}/led_joint_2" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${robot_namespace}/base_link" />
      <child link="led_link_2" />
    </joint>

    <link name="led_link_2"><!--green-->
      <visual>
        <origin xyz="0.165 0 -0.08" rpy="0 0 0" />
        <geometry>
          <cylinder radius="0.01" length="0.02"/>
        </geometry>
      </visual>
    </link>

    <gazebo reference="led_link_2">
      <visual>
        <material>
          <ambient>0 0 0 1</ambient>
          <diffuse>0 0 0 1</diffuse>
          <specular>0 0 0 1</specular>
          <emissive>0 1 0 1</emissive>
        </material>
      </visual>
    </gazebo>

                <!--led 3 joint \ link \ material-->
    <joint name="${robot_namespace}/led_joint_3" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${robot_namespace}/base_link" />
      <child link="led_link_3" />
    </joint>

    <link name="led_link_3"><!--white-->
      <visual>
        <origin xyz="0 -0.165 -0.08" rpy="0 0 0" />
        <geometry>
          <cylinder radius="0.01" length="0.02"/>
        </geometry>
      </visual>
    </link>

    <gazebo reference="led_link_3">
      <visual>
        <material>
          <ambient>0 0 0 1</ambient>
          <diffuse>0 0 0 1</diffuse>
          <specular>0 0 0 1</specular>
          <emissive>1 1 1 1</emissive>
        </material>
      </visual>
    </gazebo>



    <link name="${robot_namespace}/base_link_inertia">
      <inertial>
        <mass value="${mass}" />  <!-- [kg] -->
        <origin xyz="0 0 0" rpy="0 0 0" />
        <xacro:insert_block name="inertia" />
      </inertial>

      <visual>
        <origin xyz="-0.17 -0.17 0" rpy="-1.57 0 0" />
        <geometry>
            <mesh filename="${mesh_file}" scale="0.001 0.001 0.001" />
          <!--<xacro:if value="${use_mesh_file}">
            <mesh filename="${mesh_file}" scale="2 2 2" />
          </xacro:if>-->
          <!--<xacro:unless value="${use_mesh_file}">
            <box size="${body_width} ${body_width} ${body_height}"/>  <!-[m] [m] [m] -> 
          </xacro:unless>-->
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${body_width} ${body_width} ${body_height}" /> <!-- [m] [m] [m] -->
        </geometry>
      </collision>
    </link>


    <!-- attach multirotor_base_plugin to the base_link -->
    <!--<gazebo>
      <plugin filename="librotors_gazebo_multirotor_base_plugin.so" name="multirotor_base_plugin">
        <robotNamespace>${robot_namespace}</robotNamespace>
        <linkName>${robot_namespace}/base_link</linkName>
        <rotorVelocitySlowdownSim>${rotor_velocity_slowdown_sim}</rotorVelocitySlowdownSim>
      </plugin>
    </gazebo>-->
  </xacro:macro>

  <!-- Rotor joint and link -->
  <xacro:macro name="vertical_rotor"
    params="robot_namespace suffix direction motor_constant moment_constant parent mass_rotor radius_rotor time_constant_up time_constant_down max_rot_velocity motor_number rotor_drag_coefficient rolling_moment_coefficient color use_own_mesh mesh *origin *inertia">
    <joint name="${robot_namespace}/rotor_${motor_number}_joint" type="continuous">
      <xacro:insert_block name="origin" />
      <axis xyz="0 0 1" />
      <!-- TODO(ff): not currently set because it's not yet supported -->
      <!-- <limit effort="2000" velocity="${max_rot_velocity}" /> -->
      <parent link="${parent}" />
      <child link="${robot_namespace}/rotor_${motor_number}" />
    </joint>
    <link name="${robot_namespace}/rotor_${motor_number}">
      <inertial>
        <mass value="${mass_rotor}" /> <!-- [kg] -->
        <xacro:insert_block name="inertia" />
      </inertial>
      <visual>
        <geometry>
<!--          &lt;!&ndash; <cylinder length="0.005" radius="${radius_rotor}"/> &ndash;&gt; &lt;!&ndash; [m] &ndash;&gt;-->
<!--          <xacro:if value="${use_own_mesh}">-->
<!--            <mesh filename="${mesh}"-->
<!--              scale="1 1 1" />-->
<!--          </xacro:if>-->
<!--          <xacro:unless value="${use_own_mesh}">-->
<!--            <mesh filename="package://rotors_description/meshes/propeller_${direction}.dae"-->
<!--              scale="${radius_rotor} ${radius_rotor} ${radius_rotor}" /> &lt;!&ndash; The propeller meshes have a radius of 1m &ndash;&gt;-->
<!--            &lt;!&ndash; <box size="${2*radius_rotor} 0.01 0.005"/> &ndash;&gt;-->
<!--          </xacro:unless>-->
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.005" radius="${radius_rotor}" /> <!-- [m] -->
        </geometry>
      </collision>
    </link>
    <gazebo>
      <plugin name="${robot_namespace}_${suffix}_motor_model" filename="librotors_gazebo_motor_model.so">
        <robotNamespace>${robot_namespace}</robotNamespace>
        <jointName>${robot_namespace}/rotor_${motor_number}_joint</jointName>
        <linkName>${robot_namespace}/rotor_${motor_number}</linkName>
        <turningDirection>${direction}</turningDirection>
        <timeConstantUp>${time_constant_up}</timeConstantUp>
        <timeConstantDown>${time_constant_down}</timeConstantDown>
        <maxRotVelocity>${max_rot_velocity}</maxRotVelocity>
        <motorConstant>${motor_constant}</motorConstant>
        <momentConstant>${moment_constant}</momentConstant>
        <commandSubTopic>gazebo/command/motor_speed</commandSubTopic>
        <motorNumber>${motor_number}</motorNumber>
        <rotorDragCoefficient>${rotor_drag_coefficient}</rotorDragCoefficient>
        <rollingMomentCoefficient>${rolling_moment_coefficient}</rollingMomentCoefficient>
        <motorSpeedPubTopic>motor_speed/${motor_number}</motorSpeedPubTopic>
        <rotorVelocitySlowdownSim>${rotor_velocity_slowdown_sim}</rotorVelocitySlowdownSim>
      </plugin>
    </gazebo>
    <gazebo reference="${robot_namespace}/rotor_${motor_number}">
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>
</robot>

